### ISSUE TITLE
Export Preview

### ISSUE THREAD

**Issue by JourdanDixon** [kaishuu0123/vscode-erd#1]
Hello.  Is there a way to save the ERD preview as PDF or something similar?  I can't find anything.

**Comment by kaishuu0123** [comment]
@JourdanDixon thank you for your comment.

I will consider the correspondence.
What kind of file format do you want to save? (SVG, PDF, PNG etc)

**Comment by kaishuu0123** [comment]
(memo)
refs: https://marketplace.visualstudio.com/items?itemName=speks.flowmaker
Save SVG file.

**Comment by kaishuu0123** [comment]
@JourdanDixon 

2.0.0 release! Please use "ERD: Save as SVG" command.

**Comment by JourdanDixon** [comment]
I tried using that, but it didn't work.  Do I need to include another exe file like I do for erd-go and the 2nd one (I forget the name)?  And would it be tough to do a save as png instead?  That seems to be an easier image type for most people to use.  What do you think?

**Comment by kaishuu0123** [comment]
@JourdanDixon 

capture procedure
![save_as_svg](https://user-images.githubusercontent.com/1567423/42668110-d7893e7a-8689-11e8-9be1-909b3cd69e24.gif)

> Do I need to include another exe file like I do for erd-go and the 2nd one (I forget the name)?

No. do not need another exe file.
erd-go and dot command only.

> And would it be tough to do a save as png instead? That seems to be an easier image type for most people to use. What do you think?

hm, i will support png & pdf too.
wait a minute.
