### ISSUE TITLE
Column Label Spacing

### ISSUE THREAD

**Issue by JourdanDixon** [kaishuu0123/vscode-erd#2]
Hello.  I love the extension BTW.  I have a couple questions though.

When I add a label to a column, it doesn't add a space between the column name and label.  For example, this code:
`*Id { label: "BIGINT, NOT NULL" }`

Outputs like this:
*Id[BIGINT, NOT NULL]

I'd like it to look like this if possible, with the space:
*Id [BIGINT, NOT NULL]

Also, is there a way I could remove the brackets around the label, so it just reads like this:
*Id BIGINT, NOT NULL

**Comment by kaishuu0123** [comment]
@JourdanDixon 
thank you.
i will fix this issue with [erd-go](https://github.com/kaishuu0123/erd-go). (add label spacing)

**Comment by kaishuu0123** [comment]
@JourdanDixon 

fixed by https://github.com/kaishuu0123/erd-go/pull/5

v1.3 released.

**Comment by kaishuu0123** [comment]
![2018-07-11 11 09 20](https://user-images.githubusercontent.com/1567423/42547025-ea756dfa-84fa-11e8-9e4e-386caf3129d6.png)

**Comment by JourdanDixon** [comment]
This one is perfect.  Thank you very much.  I've been updating my ERDs to include data type information.
