### ISSUE TITLE
Some label options don't work

### ISSUE THREAD

**Issue by kvaleev** [kaishuu0123/vscode-erd#28]
Looks like some of the label options (for instance `font` and `border-color`) don't make any difference not in the preview nor on the output file.

Or I get it wrong, and the options from https://github.com/BurntSushi/erd are not implemented in this project?

**Comment by kaishuu0123** [comment]
Thanks.
Please show me the ERD code that you said would don't work.

**Comment by kvaleev** [comment]
For instance:

```
[Users] {bgcolor: "#EDEDED", size: "25", font: "Helvetica", border-color: "#A5A5A5"}
*id
role
is_active
```
Here works only `bgcolor`, other options are ignored:

![](https://www.dropbox.com/s/xyurpa3ndcvaa27/04h4f3kc.png?raw=1)

**Comment by kaishuu0123** [comment]
@kvaleev Thank you for your comment.

This problem is due to erd-go.
This issue is closed because i created an erd-go issue.
